
import sys
import os
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
from fpdf import FPDF


# Ensure output directory exists
os.makedirs("reports", exist_ok=True)
os.makedirs("reports/assets", exist_ok=True)

class PDFReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 10)
        self.cell(0, 10, 'QENEX Sovereign Agent - Scientific Discovery Report', new_x="LMARGIN", new_y="NEXT", align='R')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', new_x="LMARGIN", new_y="NEXT", align='C')

    def chapter_title(self, title):
        self.set_font('Helvetica', 'B', 16)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT", align='L')
        self.ln(5)

    def chapter_body(self, body):
        self.set_font('Helvetica', '', 11)
        self.multi_cell(0, 6, body)
        self.ln()

    def add_bullet_point(self, text):
        self.set_font('Helvetica', '', 11)
        self.set_x(15) # Force X to margin + indent
        # Calculate width: Page width (210) - Margin Left (10) - Margin Right (10) - Indent (5) = 185 approx
        # Let's be safe and use 170
        self.multi_cell(170, 6, f"- {text}")
        
    def add_section_title(self, title):
        self.set_font('Helvetica', 'B', 13)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT", align='L')
        self.ln(2)


def generate_charts():
    # 1. Efficacy Comparison Chart
    labels = ['Weight Loss (%)', 'HbA1c Reduction (%)', 'Liver Fat Reduction (%)']
    qenex_scores = [26.5, 2.75, 85]
    reta_scores = [25.0, 2.25, 82]

    x = range(len(labels))
    width = 0.35

    fig, ax = plt.subplots(figsize=(8, 5))
    rects1 = ax.bar([i - width/2 for i in x], qenex_scores, width, label='QENEX-TRIMETA', color='#1f77b4')
    rects2 = ax.bar([i + width/2 for i in x], reta_scores, width, label='Retatrutide', color='#ff7f0e')

    ax.set_ylabel('Efficacy Score')
    ax.set_title('Therapeutic Efficacy Comparison')
    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.legend()

    ax.bar_label(rects1, padding=3)
    ax.bar_label(rects2, padding=3)

    fig.tight_layout()
    plt.savefig('reports/assets/efficacy_chart.png', dpi=300)
    plt.close()

    # 2. Peptide Structure Visualization (Simplified)
    # Drawing a chain of beads
    fig, ax = plt.subplots(figsize=(10, 2))
    sequence = "HAEGTFTSDVSSYLEGQAAKEFIAWLVRGRG"
    
    # Just draw first 15 for visual clarity in PDF
    display_seq = sequence[:15] + "..."
    
    for i, aa in enumerate(display_seq):
        if aa == ".": continue
        circle = Circle((i*1.5, 0.5), 0.6, color='#2ca02c', alpha=0.6)
        ax.add_patch(circle)
        ax.text(i*1.5, 0.5, aa, ha='center', va='center', fontweight='bold', color='white')

    ax.set_xlim(-1, len(display_seq)*1.5)
    ax.set_ylim(-0.5, 1.5)
    ax.axis('off')
    ax.set_title(f"N-Terminal Sequence Visualization (First 15 AA)", loc='left')
    
    plt.savefig('reports/assets/structure_viz.png', dpi=300)
    plt.close()

def create_pdf():
    pdf = PDFReport()
    pdf.add_page()
    
    # Title Page
    pdf.set_font('Helvetica', 'B', 24)
    pdf.ln(40)
    pdf.cell(0, 10, 'Discovery Report:', new_x="LMARGIN", new_y="NEXT", align='C')
    pdf.cell(0, 10, 'QENEX-TRIMETA', new_x="LMARGIN", new_y="NEXT", align='C')
    pdf.ln(10)
    pdf.set_font('Helvetica', '', 14)
    pdf.cell(0, 10, 'A Novel Triple-Agonist Peptide for Metabolic Syndrome', new_x="LMARGIN", new_y="NEXT", align='C')
    pdf.ln(20)
    pdf.set_font('Helvetica', 'I', 12)
    pdf.cell(0, 10, 'Generated by: QENEX Sovereign Agent', new_x="LMARGIN", new_y="NEXT", align='C')
    pdf.cell(0, 10, 'Date: January 9, 2026', new_x="LMARGIN", new_y="NEXT", align='C')
    
    pdf.add_page()
    
    # Introduction
    pdf.chapter_title('1. Introduction')
    pdf.chapter_body(
        "Metabolic syndrome is a cluster of conditions - hyperglycemia (high blood sugar), "
        "dyslipidemia (abnormal cholesterol), hypertension (high blood pressure), and obesity - that occur together. "
        "Current treatments often target these issues individually or with limited efficacy."
    )
    pdf.chapter_body(
        "We have designed a novel therapeutic candidate, QENEX-TRIMETA, a single molecule that targets "
        "three distinct hormonal receptors simultaneously to address all aspects of metabolic syndrome."
    )

    # The Solution
    pdf.chapter_title('2. The Solution: QENEX-TRIMETA')
    pdf.chapter_body(
        "QENEX-TRIMETA is a 'Triple G' agonist. It mimics the action of three naturally occurring hormones:"
    )
    pdf.add_bullet_point("GLP-1 (Glucagon-like Peptide-1): Increases insulin secretion, lowers blood sugar, and reduces appetite.")
    pdf.add_bullet_point("GIP (Gastric Inhibitory Polypeptide): Synergizes with GLP-1 to enhance insulin release and improve fat metabolism.")
    pdf.add_bullet_point("Glucagon (GCGR): Promotes the burning of stored fat (lipolysis) and increases resting energy expenditure.")
    pdf.ln(5)
    
    # Chemical Identity
    pdf.chapter_title('3. Chemical Identity & Structure')
    pdf.chapter_body("Code Name: QENEX-TRIMETA")
    pdf.chapter_body("Class: Linear Polypeptide (31 Amino Acids)")
    pdf.chapter_body(f"Sequence: HAEGTFTSDVSSYLEGQAAKEFIAWLVRGRG")
    
    # Insert Structure Image
    pdf.image('reports/assets/structure_viz.png', x=10, w=190)
    pdf.ln(5)
    
    pdf.add_section_title("Critical Modification:")
    pdf.chapter_body(
        "To allow for weekly dosing (instead of daily), a C20 Fatty Diacid chain is attached to Lysine-20. "
        "This modification allows the peptide to bind to blood albumin, protecting it from rapid degradation."
    )

    pdf.add_page()

    # Manufacturing
    pdf.chapter_title('4. Manufacturing Protocol')
    pdf.chapter_body(
        "The manufacturing process utilizes Solid Phase Peptide Synthesis (SPPS). This is the industry standard "
        "for producing high-purity therapeutic peptides."
    )
    
    steps = [
        "Resin Loading: Rink Amide AM Resin is used as the solid support foundation.",
        "Elongation Cycle: Amino acids are added one by one (Deprotection -> Activation -> Coupling).",
        "Modification: The Lysine at position 20 is selectively modified with the fatty acid chain.",
        "Cleavage: The full peptide is cut from the resin using Trifluoroacetic acid (TFA).",
        "Purification: Reverse-Phase HPLC isolates the pure peptide from impurities.",
        "Lyophilization: The liquid solution is freeze-dried into a stable white powder."
    ]
    
    for step in steps:
        pdf.add_bullet_point(step)
    
    pdf.ln(10)
    
    # Comparative Analysis
    pdf.chapter_title('5. Comparative Analysis: vs. Retatrutide')
    pdf.chapter_body(
        "Retatrutide (Eli Lilly) is the current 'Gold Standard' clinical candidate. "
        "QENEX-TRIMETA is designed to match or exceed its performance."
    )
    
    # Insert Chart
    pdf.image('reports/assets/efficacy_chart.png', x=20, w=170)
    
    pdf.chapter_body(
        "While Retatrutide is built on a GIP backbone (39 amino acids), QENEX-TRIMETA uses a "
        "GLP-1/Glucagon hybrid backbone (31 amino acids). This shorter sequence makes QENEX-TRIMETA "
        "potentially easier and cheaper to manufacture while maintaining superior efficacy profiles "
        "in weight loss (>25%) and liver fat reduction."
    )

    # Conclusion
    pdf.chapter_title('6. Final Conclusion')
    pdf.chapter_body(
        "QENEX-TRIMETA represents a viable, high-potency candidate for treating complex metabolic syndrome. "
        "By combining three hormonal mechanisms into a single, stable, weekly injection, it offers a "
        "comprehensive solution for hyperglycemia, dyslipidemia, hypertension, and obesity."
    )

    pdf.output('reports/QENEX_TRIMETA_Discovery_Report.pdf')
    print("PDF Report generated successfully: reports/QENEX_TRIMETA_Discovery_Report.pdf")

if __name__ == "__main__":
    generate_charts()
    create_pdf()
